// The words on Picacho's card inside Claude and ChatGPT (the MCP Apps
// widget, widget.ts), in English, Spanish, Portuguese and Italian: one table
// per language with the same keys (press.test.ts pins them); the card picks
// the table from the host's locale and falls back to English. A change here
// is a change to the card: bump PRESS_WIDGET_URI (hosts cache a card).
//
// The fixed verdict words (S4/N2) are the door's own; nothing says
// "locked"; no plan, price in money, upgrade or checkout wording.
//
// Pure, alias-free, no imports.

export const WIDGET_TEXT_EN = {
  planTitle: "{title} · ad plan",
  yourAd: "Your ad",
  subPaint: "Nothing is painted yet. Stills first, then your OK.",
  subWait: "We're painting and checking your stills.",
  subDecide: "Your stills are painted and checked. Approve each one.",
  subFilm: "Approve each still. Filming isn't charged until you press Film.",
  subFilmInPicacho: "Approve each still here. Filming continues in Picacho.",
  subReady: "Your ad is ready.",
  subSetUp: "New product · set it up before painting",
  factStar: "Star",
  factProduct: "Product",
  factCut: "Cut",
  factChecks: "Checks",
  factQuote: "Quote",
  cutValue: "{shots} shots · {seconds} s · 9:16",
  quoteValue: "{total} credits · {paint} now, {animate} after your OK",
  quoteValuePaid: "{total} credits · {paint} paid, {animate} to film",
  quoteValueAllPaid: "{total} credits · all paid",
  balancePaint: "{now} left now · {after} after painting",
  balanceFilm: "{now} left now · {after} after filming",
  balanceLeft: "{now} credits left",
  policyLine: "If a filmed shot doesn't match, you choose: keep it, cut it, or film it again at the normal price.",
  credits: "credits",
  cr: "cr",
  actionPaint: "Paint {n} stills",
  actionReview: "Review stills",
  actionFullScreen: "Open full screen",
  actionOpen: "Open in Picacho",
  actionSetUp: "Set up your product · opens Picacho",
  actionApprove: "Approve stills",
  actionFilm: "Film {n} shots",
  actionFilmInPicacho: "Film in Picacho",
  actionPressLine: "Open the press line",
  working: "Working…",
  shortCredits: "This step needs {needed} credits; the account has {have}.",
  tryAgain: "That didn't go through. Try again.",
  face: "Face",
  product: "Product",
  match: "Match",
  didnt_match: "Didn't match",
  not_readable: "Not readable",
  product_missing: "Product missing",
  not_checked: "Not checked",
  no_one_in_shot: "No one in this shot",
  not_planned: "Not planned",
  roleHook: "The hook",
  roleCostar: "The co-star",
  roleLine: "The line",
  approved: "Approved",
  kept: "Kept",
  approve: "Approve",
  keep: "Keep as is",
  undo: "Undo",
  repaint: "Repaint · {n} cr",
  waitsForYou: "Waits for you",
  shotWaits: "Shot {n} waits for you",
  waitsLine: "Keep it as it is, or repaint it in Picacho. Filming waits for your choice.",
  houseRepainted: "We repainted this once, free",
  painting: "Painting…",
  marquee: "Press Tour",
  billing: "{star} in {product} · a Press Tour spot · {seconds} sec",
  sameAd: "The same ad as on picacho.ai",
  theQuote: "The quote",
  rowStills: "Stills · {n}",
  rowFilm: "Film · {n} shots",
  rowChecks: "Face and product checks",
  rowPosting: "Posting",
  included: "included",
  paid: "paid",
  wholeAd: "Whole ad",
  toFilm: "To film",
  toPaint: "To paint",
  posterAlt: "The first still of this ad",
  stillAlt: "Still for shot {n}",
} as const;

export type WidgetText = { readonly [K in keyof typeof WIDGET_TEXT_EN]: string };

/** Spanish (es-ES): the door's own words where the card shares them (i18n pressTour). */
const WIDGET_TEXT_ES: WidgetText = {
  planTitle: "{title} · plan del anuncio",
  yourAd: "Tu anuncio",
  subPaint: "Aún no hay nada pintado. Primero las fotos fijas, luego tu visto bueno.",
  subWait: "Estamos pintando y comprobando tus fotos fijas.",
  subDecide: "Tus fotos fijas están pintadas y comprobadas. Aprueba cada una.",
  subFilm: "Aprueba cada foto fija. El rodaje no se cobra hasta que pulses Rodar.",
  subFilmInPicacho: "Aprueba aquí cada foto fija. El rodaje sigue en Picacho.",
  subReady: "Tu anuncio está listo.",
  subSetUp: "Producto nuevo · prepáralo antes de pintar",
  factStar: "Protagonista",
  factProduct: "Producto",
  factCut: "Montaje",
  factChecks: "Comprobaciones",
  factQuote: "Presupuesto",
  cutValue: "{shots} tomas · {seconds} s · 9:16",
  quoteValue: "{total} créditos · {paint} ahora, {animate} tras tu visto bueno",
  quoteValuePaid: "{total} créditos · {paint} pagados, {animate} para rodar",
  quoteValueAllPaid: "{total} créditos · todo pagado",
  balancePaint: "Te quedan {now} · {after} después de pintar",
  balanceFilm: "Te quedan {now} · {after} después de rodar",
  balanceLeft: "Te quedan {now} créditos",
  policyLine: "Si una toma rodada no coincide, eliges tú: quedártela, quitarla o volver a rodarla al precio normal.",
  credits: "créditos",
  cr: "cr",
  actionPaint: "Pintar {n} fotos",
  actionReview: "Revisar las fotos fijas",
  actionFullScreen: "Abrir a pantalla completa",
  actionOpen: "Abrir en Picacho",
  actionSetUp: "Prepara tu producto · abre Picacho",
  actionApprove: "Aprobar las fotos fijas",
  actionFilm: "Rodar {n} tomas",
  actionFilmInPicacho: "Rodar en Picacho",
  actionPressLine: "Abrir la rueda de prensa",
  working: "Trabajando…",
  shortCredits: "Este paso necesita {needed} créditos; la cuenta tiene {have}.",
  tryAgain: "No salió. Vuelve a intentarlo.",
  face: "Cara",
  product: "Producto",
  match: "Coincide",
  didnt_match: "No coincide",
  not_readable: "No legible",
  product_missing: "Falta el producto",
  not_checked: "Sin comprobar",
  no_one_in_shot: "Nadie en esta toma",
  not_planned: "No previsto",
  roleHook: "El gancho",
  roleCostar: "El coprotagonista",
  roleLine: "La frase",
  approved: "Aprobada",
  kept: "Se queda así",
  approve: "Aprobar",
  keep: "Dejarla así",
  undo: "Deshacer",
  repaint: "Repintar · {n} cr",
  waitsForYou: "Te espera",
  shotWaits: "La toma {n} te espera",
  waitsLine: "Déjala así o repíntala en Picacho. El rodaje espera a que elijas.",
  houseRepainted: "La repintamos una vez, gratis",
  painting: "Pintando…",
  marquee: "Press Tour",
  billing: "{star} en {product} · un anuncio de Press Tour · {seconds} s",
  sameAd: "El mismo anuncio que en picacho.ai",
  theQuote: "El presupuesto",
  rowStills: "Fotos fijas · {n}",
  rowFilm: "Rodaje · {n} tomas",
  rowChecks: "Comprobación de cara y producto",
  rowPosting: "Publicación",
  included: "incluido",
  paid: "pagado",
  wholeAd: "Anuncio completo",
  toFilm: "Para rodar",
  toPaint: "Por pintar",
  posterAlt: "La primera foto fija de este anuncio",
  stillAlt: "Foto fija de la toma {n}",
};

/** Brazilian Portuguese: the door's own words where the card shares them (i18n pressTour). */
const WIDGET_TEXT_PT: WidgetText = {
  planTitle: "{title} · plano do anúncio",
  yourAd: "Seu anúncio",
  subPaint: "Nada foi pintado ainda. Primeiro as fotos fixas, depois o seu OK.",
  subWait: "Estamos pintando e conferindo suas fotos fixas.",
  subDecide: "Suas fotos fixas estão pintadas e conferidas. Aprove cada uma.",
  subFilm: "Aprove cada foto fixa. A filmagem só é cobrada quando você tocar em Filmar.",
  subFilmInPicacho: "Aprove cada foto fixa aqui. A filmagem continua no Picacho.",
  subReady: "Seu anúncio está pronto.",
  subSetUp: "Produto novo · configure antes de pintar",
  factStar: "Estrela",
  factProduct: "Produto",
  factCut: "Montagem",
  factChecks: "Conferências",
  factQuote: "Orçamento",
  cutValue: "{shots} cenas · {seconds} s · 9:16",
  quoteValue: "{total} créditos · {paint} agora, {animate} depois do seu OK",
  quoteValuePaid: "{total} créditos · {paint} pagos, {animate} para filmar",
  quoteValueAllPaid: "{total} créditos · tudo pago",
  balancePaint: "Restam {now} · {after} depois de pintar",
  balanceFilm: "Restam {now} · {after} depois de filmar",
  balanceLeft: "Restam {now} créditos",
  policyLine: "Se uma cena filmada não corresponder, você escolhe: mantê-la, tirá-la ou refilmá-la pelo preço normal.",
  credits: "créditos",
  cr: "cr",
  actionPaint: "Pintar {n} fotos",
  actionReview: "Revisar as fotos fixas",
  actionFullScreen: "Abrir em tela cheia",
  actionOpen: "Abrir no Picacho",
  actionSetUp: "Configure seu produto · abre o Picacho",
  actionApprove: "Aprovar as fotos fixas",
  actionFilm: "Filmar {n} cenas",
  actionFilmInPicacho: "Filmar no Picacho",
  actionPressLine: "Abrir a coletiva de imprensa",
  working: "Trabalhando…",
  shortCredits: "Esta etapa precisa de {needed} créditos; a conta tem {have}.",
  tryAgain: "Não deu certo. Tente de novo.",
  face: "Rosto",
  product: "Produto",
  match: "Corresponde",
  didnt_match: "Não corresponde",
  not_readable: "Ilegível",
  product_missing: "Produto ausente",
  not_checked: "Não verificado",
  no_one_in_shot: "Ninguém nesta cena",
  not_planned: "Não previsto",
  roleHook: "O gancho",
  roleCostar: "O coadjuvante",
  roleLine: "A frase",
  approved: "Aprovada",
  kept: "Mantida",
  approve: "Aprovar",
  keep: "Manter como está",
  undo: "Desfazer",
  repaint: "Repintar · {n} cr",
  waitsForYou: "Aguarda você",
  shotWaits: "A cena {n} aguarda você",
  waitsLine: "Mantenha como está ou repinte no Picacho. A filmagem aguarda sua escolha.",
  houseRepainted: "Repintamos esta uma vez, de graça",
  painting: "Pintando…",
  marquee: "Press Tour",
  billing: "{star} em {product} · um anúncio Press Tour · {seconds} s",
  sameAd: "O mesmo anúncio que no picacho.ai",
  theQuote: "O orçamento",
  rowStills: "Fotos fixas · {n}",
  rowFilm: "Filmagem · {n} cenas",
  rowChecks: "Conferência de rosto e produto",
  rowPosting: "Publicação",
  included: "incluído",
  paid: "pago",
  wholeAd: "Anúncio completo",
  toFilm: "Para filmar",
  toPaint: "A pintar",
  posterAlt: "A primeira foto fixa deste anúncio",
  stillAlt: "Foto fixa da cena {n}",
};

/** Italian: the door's own words where the card shares them (i18n pressTour). */
const WIDGET_TEXT_IT: WidgetText = {
  planTitle: "{title} · piano dello spot",
  yourAd: "Il tuo spot",
  subPaint: "Non c'è ancora niente di dipinto. Prima le foto di scena, poi il tuo OK.",
  subWait: "Stiamo dipingendo e controllando le tue foto di scena.",
  subDecide: "Le tue foto di scena sono dipinte e controllate. Approva ciascuna.",
  subFilm: "Approva ogni foto di scena. Le riprese si pagano solo quando premi Gira.",
  subFilmInPicacho: "Approva qui ogni foto di scena. Le riprese continuano in Picacho.",
  subReady: "Il tuo spot è pronto.",
  subSetUp: "Prodotto nuovo · preparalo prima di dipingere",
  factStar: "Star",
  factProduct: "Prodotto",
  factCut: "Montaggio",
  factChecks: "Controlli",
  factQuote: "Preventivo",
  cutValue: "{shots} inquadrature · {seconds} s · 9:16",
  quoteValue: "{total} crediti · {paint} ora, {animate} dopo il tuo OK",
  quoteValuePaid: "{total} crediti · {paint} pagati, {animate} per girare",
  quoteValueAllPaid: "{total} crediti · tutto pagato",
  balancePaint: "Ne hai {now} · {after} dopo averle dipinte",
  balanceFilm: "Ne hai {now} · {after} dopo le riprese",
  balanceLeft: "Ti restano {now} crediti",
  policyLine: "Se un'inquadratura girata non corrisponde, scegli tu: tenerla, toglierla o rigirarla al prezzo normale.",
  credits: "crediti",
  cr: "cr",
  actionPaint: "Dipingi {n} foto",
  actionReview: "Rivedi le foto di scena",
  actionFullScreen: "Apri a schermo intero",
  actionOpen: "Apri in Picacho",
  actionSetUp: "Prepara il tuo prodotto · apre Picacho",
  actionApprove: "Approva le foto di scena",
  actionFilm: "Gira {n} inquadrature",
  actionFilmInPicacho: "Gira in Picacho",
  actionPressLine: "Apri la conferenza stampa",
  working: "Al lavoro…",
  shortCredits: "Questo passaggio richiede {needed} crediti; l'account ne ha {have}.",
  tryAgain: "Non è andato a buon fine. Riprova.",
  face: "Volto",
  product: "Prodotto",
  match: "Corrisponde",
  didnt_match: "Non corrisponde",
  not_readable: "Illeggibile",
  product_missing: "Prodotto assente",
  not_checked: "Non verificato",
  no_one_in_shot: "Nessuno in questa inquadratura",
  not_planned: "Non previsto",
  roleHook: "L'aggancio",
  roleCostar: "Il co-protagonista",
  roleLine: "La battuta",
  approved: "Approvata",
  kept: "Tenuta",
  approve: "Approva",
  keep: "Tienila così",
  undo: "Annulla",
  repaint: "Ridipingi · {n} cr",
  waitsForYou: "Ti aspetta",
  shotWaits: "L'inquadratura {n} ti aspetta",
  waitsLine: "Tienila così o ridipingila in Picacho. Le riprese aspettano la tua scelta.",
  houseRepainted: "L'abbiamo ridipinta una volta, gratis",
  painting: "Pittura in corso…",
  marquee: "Press Tour",
  billing: "{star} in {product} · uno spot Press Tour · {seconds} s",
  sameAd: "Lo stesso spot che su picacho.ai",
  theQuote: "Il preventivo",
  rowStills: "Foto di scena · {n}",
  rowFilm: "Riprese · {n} inquadrature",
  rowChecks: "Controlli di volto e prodotto",
  rowPosting: "Pubblicazione",
  included: "incluso",
  paid: "pagato",
  wholeAd: "Spot completo",
  toFilm: "Per girare",
  toPaint: "Da dipingere",
  posterAlt: "La prima foto di scena di questo spot",
  stillAlt: "Foto di scena dell'inquadratura {n}",
};

/** Tables by locale: the card picks by the host's language and falls back to English. */
export const WIDGET_TEXTS: Readonly<Record<string, WidgetText>> = {
  en: WIDGET_TEXT_EN,
  es: WIDGET_TEXT_ES,
  pt: WIDGET_TEXT_PT,
  it: WIDGET_TEXT_IT,
};
