import zlib from "node:zlib";
import sharp from "sharp";
import { beforeAll, describe, expect, it } from "vitest";
import {
  MAX_LONG_EDGE,
  MIN_SHORT_SIDE,
  ProductImageError,
  hammingDistance,
  isSamePicture,
  normalizeProductImage,
  perceptualHash,
  prepareProductImages,
  worstBlockDifference,
  type FetchedImage,
} from "./product-images";
import { SVG_LOGO_REFUSED, SafeFetchError, type Resolver, type Transport } from "./safe-fetch";

// Every picture here is generated by sharp from a pixel pattern; nothing is
// downloaded. The batch tests inject the download function, and one runs the
// real safeFetch against a table DNS and a fake transport.

type Rgb = [number, number, number];
type Pattern = (x: number, y: number, w: number, h: number) => Rgb;

const grey = (v: number): Rgb => [v, v, v];
const PATTERNS: Record<string, Pattern> = {
  verticalStripes: (x, _y, w) => grey(Math.floor((x / w) * 4) % 2 ? 230 : 25),
  horizontalStripes: (_x, y, _w, h) => grey(Math.floor((y / h) * 4) % 2 ? 230 : 25),
  checker: (x, y, w, h) => grey((Math.floor((x / w) * 3) + Math.floor((y / h) * 3)) % 2 ? 235 : 20),
  gradientRight: (x, _y, w) => grey(Math.round((x / w) * 255)),
  gradientDown: (_x, y, _w, h) => grey(Math.round((y / h) * 255)),
  centreDisc: (x, y, w, h) => grey(Math.hypot(x / w - 0.5, y / h - 0.5) < 0.3 ? 20 : 235),
  cornerDisc: (x, y, w, h) => grey(Math.hypot(x / w - 0.25, y / h - 0.25) < 0.2 ? 20 : 235),
  bottomRightBlock: (x, y, w, h) => grey(x / w > 0.55 && y / h > 0.55 ? 20 : 235),
  diagonal: (x, y, w, h) => grey(x / w + y / h < 1 ? 30 : 225),
  cross: (x, y, w, h) => grey(Math.abs(x / w - 0.5) < 0.1 || Math.abs(y / h - 0.5) < 0.1 ? 20 : 235),
  leftBar: (x, _y, w) => grey(x / w < 0.3 ? 20 : 235),
};

function rgbDisc(colour: Rgb): Pattern {
  return (x, y, w, h) => (Math.hypot(x / w - 0.5, y / h - 0.6) < 0.3 ? colour : [245, 245, 245]);
}

/** A centred, symmetric bottle on white, with `label` painted on its front (u, v in 0–1 across the label). */
function bottle(label: (u: number, v: number) => number): Pattern {
  return (x, y, w, h) => {
    const u = x / w;
    const v = y / h;
    if (Math.abs(u - 0.5) < 0.18 && v > 0.15 && v < 0.92) {
      if (Math.abs(u - 0.5) < 0.15 && v > 0.4 && v < 0.7) return grey(label((u - 0.35) / 0.3, (v - 0.4) / 0.3));
      return [40, 90, 60];
    }
    if (Math.abs(u - 0.5) < 0.06 && v > 0.05 && v <= 0.15) return grey(30);
    return grey(248);
  };
}
const BOTTLE_FRONT = bottle((u, v) => (v > 0.3 && v < 0.5 && u > 0.1 && u < 0.9 ? 20 : 235));
const BOTTLE_BACK = bottle((u, v) => (Math.floor(v * 16) % 2 === 0 && v > 0.55 && u > 0.15 && u < 0.85 && Math.floor(u * 30) % 2 === 0 ? 60 : 235));

function raw(pattern: Pattern, width: number, height: number): Buffer {
  const out = Buffer.alloc(width * height * 3);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const [r, g, b] = pattern(x, y, width, height);
      const o = (y * width + x) * 3;
      out[o] = r;
      out[o + 1] = g;
      out[o + 2] = b;
    }
  }
  return out;
}

function picture(pattern: Pattern, width: number, height: number) {
  return sharp(raw(pattern, width, height), { raw: { width, height, channels: 3 } });
}

async function jpeg(pattern: Pattern, width = 640, height = 640, quality = 90): Promise<Buffer> {
  return picture(pattern, width, height).jpeg({ quality }).toBuffer();
}

/** A PNG whose header claims `width` × `height` and whose pixel data is a few bytes. */
function pngHeaderOnly(width: number, height: number): Buffer {
  const chunk = (type: string, data: Buffer) => {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(zlib.crc32(body) >>> 0);
    return Buffer.concat([length, body, crc]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // RGB
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", zlib.deflateSync(Buffer.alloc(16))),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

async function reasonOf(p: Promise<unknown>): Promise<string> {
  try {
    await p;
    return "resolved";
  } catch (err) {
    if (err instanceof ProductImageError) return err.reason;
    throw err;
  }
}

function fromTable(table: Record<string, Buffer | Error>, log: string[] = [], delay?: (url: string) => number) {
  return async (url: string, signal: AbortSignal): Promise<FetchedImage> => {
    log.push(url);
    if (delay) {
      await new Promise<void>((resolve, reject) => {
        const t = setTimeout(resolve, delay(url));
        signal.addEventListener("abort", () => {
          clearTimeout(t);
          reject(new SafeFetchError("aborted"));
        });
      });
    }
    const entry = table[url];
    if (entry === undefined) throw new SafeFetchError("http_status", "status 404", 404);
    if (entry instanceof Error) throw entry;
    return { body: entry, url };
  };
}

// Every block below decodes and re-encodes real pictures with sharp (1400 px
// squares among them). Alone that takes well under vitest's 5 s default; in
// the full suite, beside other sessions' builds and an emulator on an 8 GB
// machine, it did not (review F6: 1 to 3 "timed out in 5000ms" in
// isSamePicture across two runs, 26/26 alone). The same explicit budget
// recast/trim.test.ts and media/mp4-join.test.ts give their real-binary work.
const SHARP_TIMEOUT = { timeout: 30_000 };

const distinct: Record<string, Buffer> = {};
beforeAll(async () => {
  for (const [name, pattern] of Object.entries(PATTERNS)) distinct[name] = await jpeg(pattern);
}, 60_000);

describe("perceptualHash", SHARP_TIMEOUT, () => {
  it("is stable, sees an inverted picture as far away, and needs 32 x 32 values", () => {
    const values = Array.from({ length: 1024 }, (_, i) => ((i % 32) * 7 + Math.floor(i / 32) * 3) % 256);
    const { hash, mask } = perceptualHash(values);
    expect(hash).toMatch(/^[0-9a-f]{16}$/);
    expect(mask).toMatch(/^[0-9a-f]{16}$/);
    expect(perceptualHash(values).hash).toBe(hash);
    expect(hammingDistance(hash, perceptualHash(values.map((v) => 255 - v)).hash)).toBeGreaterThan(40);
    expect(() => perceptualHash([1, 2, 3])).toThrow(RangeError);
  });

  it("masks out the terms a symmetric picture zeroes, and trusts nothing in a flat one", () => {
    const disc = Array.from({ length: 1024 }, (_, i) => (Math.hypot((i % 32) - 15.5, Math.floor(i / 32) - 15.5) < 9 ? 20 : 235));
    const trusted = (mask: string) => hammingDistance(mask, "0".repeat(16));
    expect(trusted(perceptualHash(disc).mask)).toBeLessThan(32);
    expect(perceptualHash(new Array(1024).fill(128)).mask).toBe("0".repeat(16));
  });

  it("counts differing bits, optionally under a mask", () => {
    expect(hammingDistance("ff", "0f")).toBe(4);
    expect(hammingDistance("ff", "0f", "0f")).toBe(0);
    expect(hammingDistance("ff", "fff")).toBe(64);
    expect(hammingDistance("zz", "ff")).toBe(64);
  });

  it("tells every test pattern apart (the fixtures below rely on it)", async () => {
    const prints = await Promise.all(Object.values(distinct).map(async (buf) => (await normalizeProductImage(buf)).fingerprint));
    for (let i = 0; i < prints.length; i++) {
      for (let j = i + 1; j < prints.length; j++) expect(isSamePicture(prints[i], prints[j])).toBe(false);
    }
  });
});

describe("isSamePicture", SHARP_TIMEOUT, () => {
  it("matches a symmetric packshot across sizes, qualities and formats", async () => {
    const a = await normalizeProductImage(await jpeg(BOTTLE_FRONT, 1400, 1400, 95));
    const b = await normalizeProductImage(await jpeg(BOTTLE_FRONT, 800, 800, 55));
    const c = await normalizeProductImage(await picture(BOTTLE_FRONT, 1000, 1000).webp({ quality: 50 }).toBuffer());
    const d = await normalizeProductImage(await jpeg(PATTERNS.centreDisc, 1400, 1400, 95));
    const e = await normalizeProductImage(await jpeg(PATTERNS.centreDisc, 800, 800, 55));
    expect(isSamePicture(a.fingerprint, b.fingerprint)).toBe(true);
    expect(isSamePicture(a.fingerprint, c.fingerprint)).toBe(true);
    expect(isSamePicture(d.fingerprint, e.fingerprint)).toBe(true);
    expect(worstBlockDifference(a.fingerprint.thumb, b.fingerprint.thumb)).toBeLessThan(8);
  });

  it("keeps the back of the bottle apart from its front (same silhouette, different label)", async () => {
    const front = await normalizeProductImage(await jpeg(BOTTLE_FRONT, 1200, 1200, 92));
    const back = await normalizeProductImage(await jpeg(BOTTLE_BACK, 1200, 1200, 92));
    expect(isSamePicture(front.fingerprint, back.fingerprint)).toBe(false);
    expect(worstBlockDifference(front.fingerprint.thumb, back.fingerprint.thumb)).toBeGreaterThan(40);
  });

  it("keeps a different framing of the same product apart", async () => {
    const square = await normalizeProductImage(await jpeg(BOTTLE_FRONT, 1000, 1000));
    const tall = await normalizeProductImage(await jpeg(BOTTLE_FRONT, 800, 1000));
    expect(isSamePicture(square.fingerprint, tall.fingerprint)).toBe(false);
  });
});

describe("normalizeProductImage", SHARP_TIMEOUT, () => {
  it("re-encodes a JPEG and drops its EXIF", async () => {
    const input = await picture(PATTERNS.centreDisc, 800, 800)
      .withExif({ IFD0: { Copyright: "secret owner", Artist: "camera serial 1234" } })
      .jpeg()
      .toBuffer();
    expect((await sharp(input).metadata()).exif).toBeDefined();
    const out = await normalizeProductImage(input);
    const meta = await sharp(out.data).metadata();
    expect(out.mime).toBe("image/jpeg");
    expect(meta.format).toBe("jpeg");
    expect(meta.exif).toBeUndefined();
    expect(meta.xmp).toBeUndefined();
    expect(meta.icc).toBeUndefined();
    expect([out.width, out.height]).toEqual([800, 800]);
    expect(out.bytes).toBe(out.data.length);
    expect(out.sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(out.data.includes(Buffer.from("secret owner"))).toBe(false);
  });

  it("applies the EXIF rotation before throwing the EXIF away", async () => {
    const input = await picture(PATTERNS.leftBar, 900, 600).withMetadata({ orientation: 6 }).jpeg().toBuffer();
    const out = await normalizeProductImage(input);
    expect([out.width, out.height]).toEqual([600, 900]);
    expect((await sharp(out.data).metadata()).orientation).toBeUndefined();
  });

  it("keeps transparency as PNG", async () => {
    const rgba = Buffer.alloc(600 * 600 * 4);
    for (let i = 0; i < 600 * 600; i++) {
      const x = i % 600;
      rgba[i * 4] = 200;
      rgba[i * 4 + 3] = x < 300 ? 255 : 0;
    }
    const input = await sharp(rgba, { raw: { width: 600, height: 600, channels: 4 } }).png().toBuffer();
    const out = await normalizeProductImage(input);
    expect(out.mime).toBe("image/png");
    const meta = await sharp(out.data).metadata();
    expect(meta.format).toBe("png");
    expect(meta.hasAlpha).toBe(true);
  });

  it("turns WebP and AVIF into ordinary JPEG", async () => {
    const webp = await picture(PATTERNS.checker, 600, 600).webp().toBuffer();
    const avif = await picture(PATTERNS.checker, 600, 600).avif({ effort: 0 }).toBuffer();
    for (const input of [webp, avif]) {
      const out = await normalizeProductImage(input);
      expect(out.mime).toBe("image/jpeg");
      expect((await sharp(out.data).metadata()).format).toBe("jpeg");
    }
  });

  it("caps the long edge at 2048 px without enlarging", async () => {
    const out = await normalizeProductImage(await jpeg(PATTERNS.gradientRight, 3000, 1000));
    expect([out.width, out.height]).toEqual([MAX_LONG_EDGE, 683]);
    const small = await normalizeProductImage(await jpeg(PATTERNS.gradientRight, 700, 520));
    expect([small.width, small.height]).toEqual([700, 520]);
  });

  it("refuses anything under 512 px on the short side, and takes exactly 512", async () => {
    expect(await reasonOf(normalizeProductImage(await jpeg(PATTERNS.gradientDown, 1000, 400)))).toBe("too_small");
    expect(await reasonOf(normalizeProductImage(await jpeg(PATTERNS.gradientDown, 511, 900)))).toBe("too_small");
    const ok = await normalizeProductImage(await jpeg(PATTERNS.gradientDown, MIN_SHORT_SIDE, MIN_SHORT_SIDE));
    expect(ok.width).toBe(512);
  });

  it("refuses a strip the long-edge cap would take under 512 px, so every kept picture is at least 512", async () => {
    // 600 x 3000 passes the 512 check as downloaded but would leave as 410 x 2048.
    expect(await reasonOf(normalizeProductImage(await jpeg(PATTERNS.gradientDown, 600, 3000)))).toBe("bad_shape");
    expect(await reasonOf(normalizeProductImage(await jpeg(PATTERNS.gradientRight, 3000, 600)))).toBe("bad_shape");
    // Right at 4:1, and just past it where the rounding still lands on 512, it is kept.
    for (const [w, h] of [
      [512, 2048],
      [513, 2053],
      [2081, 520],
    ]) {
      const out = await normalizeProductImage(await jpeg(PATTERNS.gradientDown, w, h));
      expect(Math.min(out.width, out.height)).toBe(MIN_SHORT_SIDE);
      expect(Math.max(out.width, out.height)).toBe(MAX_LONG_EDGE);
    }
  });

  it("refuses a pixel flood from its header, before decoding", async () => {
    const bomb = pngHeaderOnly(60_000, 60_000);
    expect(bomb.length).toBeLessThan(200);
    const started = Date.now();
    expect(await reasonOf(normalizeProductImage(bomb))).toBe("too_many_pixels");
    expect(Date.now() - started).toBeLessThan(1_000);
  });

  it("honours a lower pixel ceiling", async () => {
    const input = await jpeg(PATTERNS.cross, 1000, 1000);
    expect(await reasonOf(normalizeProductImage(input, { maxInputPixels: 500_000 }))).toBe("too_many_pixels");
    expect((await normalizeProductImage(input, { maxInputPixels: 2_000_000 })).width).toBe(1000);
  });

  it("refuses SVG with the logo sentence", async () => {
    const svg = Buffer.from('<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" width="900" height="900"><rect width="900" height="900"/></svg>');
    try {
      await normalizeProductImage(svg);
      throw new Error("resolved");
    } catch (err) {
      expect(err).toBeInstanceOf(ProductImageError);
      expect((err as ProductImageError).reason).toBe("svg_refused");
      expect((err as ProductImageError).message).toBe("Upload your logo as a PNG");
    }
  });

  it("refuses what is not a picture, formats we do not take, and truncated files", async () => {
    expect(await reasonOf(normalizeProductImage(Buffer.from("<!doctype html><html><body>404</body></html>")))).toBe("not_an_image");
    expect(await reasonOf(normalizeProductImage(Buffer.alloc(0)))).toBe("not_an_image");
    const gif = await picture(PATTERNS.cross, 600, 600).gif().toBuffer();
    expect(await reasonOf(normalizeProductImage(gif))).toBe("unsupported_format");
    const whole = await jpeg(PATTERNS.diagonal, 900, 900);
    expect(await reasonOf(normalizeProductImage(whole.subarray(0, Math.floor(whole.length / 2))))).toBe("decode_failed");
  });
});

describe("prepareProductImages", SHARP_TIMEOUT, () => {
  it("keeps distinct pictures in the order given, whatever order they download in", async () => {
    const names = ["verticalStripes", "horizontalStripes", "checker", "centreDisc", "cornerDisc"];
    const table = Object.fromEntries(names.map((n) => [`https://cdn.example.net/${n}.jpg`, distinct[n]]));
    const delays = [60, 5, 40, 1, 20];
    const result = await prepareProductImages(Object.keys(table), {
      fetchImage: fromTable(table, [], (url) => delays[Object.keys(table).indexOf(url)]),
      concurrency: 4,
    });
    expect(result.images.map((i) => i.sourceUrl)).toEqual(Object.keys(table));
    expect(result.rejected).toEqual([]);
  });

  it("drops the same picture at another size and quality, but keeps a second colourway and the back label", async () => {
    const big = await jpeg(PATTERNS.centreDisc, 1400, 1400, 95);
    const smaller = await jpeg(PATTERNS.centreDisc, 800, 800, 55);
    const red = await jpeg(rgbDisc([200, 30, 30]), 700, 700);
    const blue = await jpeg(rgbDisc([30, 40, 200]), 700, 700);
    const table = {
      "https://cdn.example.net/disc-2048.jpg": big,
      "https://cdn.example.net/disc-800.jpg": smaller,
      "https://cdn.example.net/disc-800-again.jpg": smaller,
      "https://cdn.example.net/mug-red.jpg": red,
      "https://cdn.example.net/mug-blue.jpg": blue,
      "https://cdn.example.net/bottle-front.jpg": await jpeg(BOTTLE_FRONT, 900, 900),
      "https://cdn.example.net/bottle-back.jpg": await jpeg(BOTTLE_BACK, 900, 900),
    };
    const result = await prepareProductImages(Object.keys(table), { fetchImage: fromTable(table) });
    expect(result.images.map((i) => i.sourceUrl)).toEqual([
      "https://cdn.example.net/disc-2048.jpg",
      "https://cdn.example.net/mug-red.jpg",
      "https://cdn.example.net/mug-blue.jpg",
      "https://cdn.example.net/bottle-front.jpg",
      "https://cdn.example.net/bottle-back.jpg",
    ]);
    expect(result.rejected).toEqual([
      { url: "https://cdn.example.net/disc-800.jpg", reason: "duplicate", message: null, detail: "https://cdn.example.net/disc-2048.jpg" },
      { url: "https://cdn.example.net/disc-800-again.jpg", reason: "duplicate", message: null, detail: "https://cdn.example.net/disc-2048.jpg" },
    ]);
  });

  it("keeps at most 8 and starts nothing once it has them", async () => {
    const names = Object.keys(PATTERNS); // 11 distinct
    const table = Object.fromEntries(names.map((n) => [`https://cdn.example.net/${n}.jpg`, distinct[n]]));
    const log: string[] = [];
    const result = await prepareProductImages(Object.keys(table), { fetchImage: fromTable(table, log), concurrency: 1 });
    expect(result.images).toHaveLength(8);
    expect(result.images.map((i) => i.sourceUrl)).toEqual(Object.keys(table).slice(0, 8));
    expect(log).toHaveLength(8);
  });

  it("tries at most 16 candidates and each URL once", async () => {
    const urls = Array.from({ length: 30 }, (_, i) => `https://cdn.example.net/missing-${i % 20}.jpg`);
    const log: string[] = [];
    const result = await prepareProductImages(urls, { fetchImage: fromTable({}, log) });
    expect(new Set(log).size).toBe(log.length);
    expect(log).toHaveLength(16);
    expect(result.images).toEqual([]);
    expect(result.rejected).toHaveLength(16);
    expect(result.rejected[0]).toEqual({ url: urls[0], reason: "fetch_failed", message: null, detail: "http_status" });
  });

  it("says why each candidate was refused", async () => {
    const svg = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');
    const table: Record<string, Buffer | Error> = {
      "https://cdn.example.net/ok.jpg": distinct.checker,
      "https://cdn.example.net/logo.svg": new SafeFetchError("svg_refused"),
      "https://cdn.example.net/inline.svg": svg,
      "https://cdn.example.net/huge.jpg": new SafeFetchError("too_large"),
      "https://cdn.example.net/internal.jpg": new SafeFetchError("address_blocked"),
      "https://cdn.example.net/slow.jpg": new SafeFetchError("timeout"),
      "https://cdn.example.net/anim.gif": new SafeFetchError("content_type_not_allowed"),
      "https://cdn.example.net/page.jpg": new SafeFetchError("not_an_image"),
      "http://cdn.example.net:8080/x.jpg": new SafeFetchError("port_not_allowed"),
      "https://cdn.example.net/thumb.jpg": await jpeg(PATTERNS.cross, 300, 300),
      "https://cdn.example.net/boom.jpg": new Error("socket hang up"),
    };
    const result = await prepareProductImages(Object.keys(table), { fetchImage: fromTable(table) });
    expect(result.images.map((i) => i.sourceUrl)).toEqual(["https://cdn.example.net/ok.jpg"]);
    expect(result.rejected.map((r) => [r.url.split("/").pop(), r.reason, r.message])).toEqual([
      ["logo.svg", "svg_refused", SVG_LOGO_REFUSED],
      ["inline.svg", "svg_refused", SVG_LOGO_REFUSED],
      ["huge.jpg", "too_large", null],
      ["internal.jpg", "fetch_failed", null],
      ["slow.jpg", "timeout", null],
      ["anim.gif", "unsupported_format", null],
      ["page.jpg", "not_an_image", null],
      ["x.jpg", "invalid_url", null],
      ["thumb.jpg", "too_small", null],
      ["boom.jpg", "fetch_failed", null],
    ]);
    expect(result.rejected.find((r) => r.url.endsWith("internal.jpg"))?.detail).toBe("address_blocked");
  });

  it("stops at the deadline: in-flight downloads are aborted and the rest never start", async () => {
    const urls = ["https://cdn.example.net/a.jpg", "https://cdn.example.net/b.jpg", "https://cdn.example.net/c.jpg"];
    const log: string[] = [];
    const started = Date.now();
    const result = await prepareProductImages(urls, {
      fetchImage: fromTable({}, log, () => 60_000),
      concurrency: 1,
      deadlineMs: 50,
    });
    expect(Date.now() - started).toBeLessThan(2_000);
    expect(log).toEqual(["https://cdn.example.net/a.jpg"]);
    expect(result.rejected).toEqual([
      { url: urls[0], reason: "timeout", message: null, detail: "aborted" },
      { url: urls[1], reason: "timeout", message: null, detail: "not_started" },
      { url: urls[2], reason: "timeout", message: null, detail: "not_started" },
    ]);
  });

  it("ignores junk in the list", async () => {
    const result = await prepareProductImages(["", "   ", 42 as unknown as string, null as unknown as string], { fetchImage: fromTable({}) });
    expect(result).toEqual({ images: [], rejected: [] });
    expect(await prepareProductImages(undefined as unknown as string[])).toEqual({ images: [], rejected: [] });
  });

  it("downloads through the real safeFetch: pinned, typed by bytes, blocked addresses refused", async () => {
    const png = await picture(PATTERNS.bottomRightBlock, 700, 700).png().toBuffer();
    const resolve: Resolver = async (host) =>
      host === "cdn.example.net" ? [{ address: "151.101.1.1", family: 4 }] : [{ address: "10.1.2.3", family: 4 }];
    const connectedTo: string[] = [];
    const transport: Transport = async (req) => {
      connectedTo.push(`${req.url.href}@${req.address}`);
      return {
        status: 200,
        headers: { "content-type": "application/octet-stream" },
        body: (async function* () {
          yield png;
        })(),
        destroy: () => {},
      };
    };
    const result = await prepareProductImages(["http://cdn.example.net/p.png", "https://internal.example.com/p.png"], {
      fetchOptions: { resolve, transport },
    });
    expect(result.images).toHaveLength(1);
    expect(result.images[0].finalUrl).toBe("https://cdn.example.net/p.png");
    expect(result.images[0].mime).toBe("image/jpeg");
    expect(result.rejected).toEqual([{ url: "https://internal.example.com/p.png", reason: "fetch_failed", message: null, detail: "address_blocked" }]);
    expect(connectedTo).toEqual(["https://cdn.example.net/p.png@151.101.1.1"]);
  });
});
