-- Rows whose files are gone read as deleted, because they are.
--
-- A storage cleanup (the 9 September purge, and possibly earlier ones)
-- removed these rows' files while the rows kept status "succeeded", so History showed a healthy tile over a 404
-- and the player span forever (operator report, 2026-09-11). Soft-deleting
-- mirrors what deleteGeneration leaves for a row the owner removes in the
-- app: deleted_at set, the ledger untouched, hidden from History and from
-- every gallery. Generated by scripts/sweep-missing-files.mjs, which
-- HEAD-checked every succeeded row's file on 2026-09-10;
-- re-run it any time to regenerate this list.

update public.generations
   set deleted_at = now()
 where deleted_at is null
   and id in (
     'b2983dc6-b8f2-4183-a80b-5b00364501db',  -- 2026-09-04 video
     'd66ffff2-057e-4490-86b4-832d88f8768c',  -- 2026-09-04 video
     '7bc89bda-26e9-40c2-aa13-25d700301734',  -- 2026-09-04 video
     '903caff2-28fb-4539-8a36-5f9c19881bbe',  -- 2026-09-04 video
     '49529d61-a3ac-4389-8def-6b49ee4acaf7',  -- 2026-09-04 image
     'a7ec0265-766b-4e5d-9ac7-a20df144806f',  -- 2026-09-04 image
     'a8524401-69cf-4981-9dbc-ca7c482d5fee',  -- 2026-09-02 image
     '5a15ad3e-bfcd-404c-9f85-c9f78ae92488',  -- 2026-09-01 image
     '409c04fe-5a81-4151-a9d6-fedfbd842cc3',  -- 2026-08-31 image
     'a45c9116-77b2-44b8-bf9b-4a155cb17afb',  -- 2026-08-31 image
     'a50d3789-cb2a-44a4-8719-b5d017911822',  -- 2026-08-29 image
     '621f18fb-2681-46a1-bda7-f1d664f8b584',  -- 2026-08-28 image
     '413bc10c-40d4-447e-baea-4c28fc5fdd70',  -- 2026-08-28 image
     'fa6e9ae3-ddf4-452e-9896-0a9fbcbf0b19',  -- 2026-08-28 image
     'd6cc30a0-40c3-4087-ad9c-983ca3234e14',  -- 2026-08-27 image
     '2aa83c91-1045-4f54-9d9f-955776b82312',  -- 2026-08-26 image
     '91296ed5-a9ac-4fa1-a86e-e57f46240a52',  -- 2026-08-26 image
     '5cb5a07e-09c6-402b-bd55-f4439c1e37ed',  -- 2026-08-25 image
     '0201e930-fba9-4ae5-80dc-63b45305e669',  -- 2026-08-24 image
     '795bb4b5-9679-4a75-b86c-71d389e7a2ba',  -- 2026-08-24 image
     '1512d917-f213-410d-877e-f34575fc7edc',  -- 2026-08-24 image
     '59d6437e-7353-4966-98f1-0d220bc8a604',  -- 2026-08-24 image
     'db19f8fe-6dcd-4c31-a950-74a335300c2b',  -- 2026-08-22 image
     '88ee26f6-b228-40d5-8c74-a59b260db137',  -- 2026-08-20 image
     'cba885e4-bd99-43a6-a9db-cc93e8b20c4a',  -- 2026-08-20 image
     'a10e7b48-3f13-4bb0-9649-fc16446a05ff',  -- 2026-08-20 image
     '62c8ac6c-bcfa-42dd-a278-bdc28ce5c9f6',  -- 2026-08-20 image
     '2628e080-aaab-4724-a641-35084317edfd',  -- 2026-08-20 image
     'ed8702dc-72c3-4948-9a19-67cd10db5292',  -- 2026-08-20 image
     '1f9b1bbd-5ed9-48ab-9314-5145b28b66ad',  -- 2026-08-20 image
     'f3d04a26-5dbb-443f-849c-b8203b3bcb78',  -- 2026-08-20 image
     '5ac1dda7-a9a7-4596-9f29-dc9d947c112a',  -- 2026-08-18 image
     '81015a48-2aa7-48de-89c9-f92d3afe033b',  -- 2026-08-18 image
     '481c595b-568d-494d-b675-79b9ad71d4df',  -- 2026-08-18 image
     'c23e3639-08b4-4c4f-87fd-8d364451f766',  -- 2026-08-18 image
     'feb2e546-7e0f-4ef0-a259-d9dcc43f8051',  -- 2026-08-18 image
     'aac19f0b-c177-41d0-bc33-13bb618bfbff',  -- 2026-08-17 image
     'c8aeb00e-bf87-45b2-9f1a-53cc7704bb58',  -- 2026-08-17 image
     '5d33caf2-1880-4336-a684-27450dbe8f68',  -- 2026-08-17 image
     '70f62c05-5b2e-434b-be7c-eb03556711ae'   -- 2026-08-17 image
   );

-- Verify: select count(*) from generations where deleted_at is null and id in (…) -> 0 rows.

-- Community posts snapshotting dead media (operator's call — a delete removes
-- them from the public feed):
-- delete from public.community_posts where id = 'df0f5e0b-0ea8-4131-9c8a-8600ebb73f82';
-- delete from public.community_posts where id = '0f3824ec-abe8-42c8-a814-6ed7ba00b711';
-- delete from public.community_posts where id = 'cd159fa1-e115-4640-83a0-9146f9ffd6ff';
-- delete from public.community_posts where id = 'bdbc6493-0d2b-48ee-92ec-37706d9ab2af';
-- delete from public.community_posts where id = '5e26b0d0-65a1-4e88-a301-817d8c2933e5';
-- delete from public.community_posts where id = '21f4fec0-39c2-44eb-9d65-406249a0de8f';
