// The one-tap photo effects each provider takes, read from fal's own API
// schemas on 2026-09-29 (https://fal.ai/api/openapi/queue/openapi.json?endpoint_id=…),
// minus what Picacho doesn't offer: other companies' brands and franchises,
// adult and gun effects, religious figures, seasonal ads, and templates that
// need two or three photos. A name here is sent to the provider exactly as
// written — a provider that renames one refuses it, and the job says so.

/** fal-ai/pixverse/v5.5/effects — `effect`. */
export const PIXVERSE_EFFECTS: readonly string[] = [
  "Muscle Surge",
  "Anything, Robot",
  "The Tiger Touch",
  "Hug",
  "Holy Wings",
  "Microwave",
  "Zombie Mode",
  "Baby Face",
  "Long Hair Magic",
  "Leggy Run",
  "Fin-tastic Mermaid",
  "Punch Face",
  "Creepy Devil Smile",
  "Thunder God",
  "Eye Zoom Challenge",
  "Baby Arrived",
  "Werewolf Rage",
  "Bald Swipe",
  "BOOM DROP",
  "Huge Cutie",
  "Liquid Metal",
  "Sharksnap!",
  "Dust Me Away",
  "3D Figurine Factor",
  "Earth Zoom",
  "Vroom Dance",
  "Dragon Evoker",
  "Package Explosion",
  "Dishes Served",
  "Tree doll",
  "The Bicep Flex",
  "London Elite Vibe",
  "Flora Nymph Gown",
  "It's Snowy",
  "Starlight Gift Box",
  "Giant Product",
  "Truck Fashion Shoot",
  "Shoal Surround",
  "Mechanical Assembly",
  "Product close-up",
  "Parachute Delivery",
  "Dreamlike Cloud",
  "Macaron Machine",
  "3D Figurine Factory",
  "The Exclusive First Class",
  "Art Zoom Challenge",
  "I Quit",
  "Hitchcock Dolly Zoom",
  "Smell the Lens",
  "I believe I can fly",
  "Strikout Dance",
  "Courtside Cam",
  "Pit Crew Moment",
  "K-Baseball Sprint",
  "Toddler Doodle",
  "Idol Ending",
  "Apex Dance",
  "OmniHero Forge",
  "Palm Decode",
  "The Age Ripple",
  "My Future Is Limitless",
  "Knee Slide",
  "Epic Goal Save",
  "Sideline Ball Boy",
  "Cup Celebration",
  "Victory Roar",
  "Vuvuzela Fan",
  "World Champion Lift",
  "Tunnel to Captain",
  "Liquid Soccer Morph",
  "Jump Into Crowd 2",
  "Golden Pitch Crasher",
  "Stadium Fan Cam",
  "Broadcast Moto GP",
  "The Grotesque Clay",
  "Rookie Star Card",
  "The Final Hug",
  "Sharp Post-Match Comment",
  "Street Maverick",
  "Pitch Legend",
  "One Step At A Time",
  "Birthday Mirror",
  "Superstar Lobby",
  "Final Battle Room",
  "Top of the World",
  "Mini Me Unboxed",
  "WonderPOP Surprise",
  "What a Day",
  "The Last Leap at Sunset",
  "Tiny Sticker Chef Chaos",
  "Mini Squeeze Toy",
  "Street Fashion Caricature",
  "Mini Me Makeover",
  "Street Art Awakening",
  "Blocky Mini-Me",
  "MiniSocial Recharge",
  "My Little Perler Charm",
  "Where did this cobweb come from?",
  "Holy Beast Summoning Technique",
  "Pet Editorial",
  "Pixel World",
  "Mint in Box",
  "Hands up, Hand",
  "Somber Embrace",
  "Beam me up",
  "Suit Swagger",
];

/** fal-ai/wan-effects — `effect_type`. */
export const WAN_EFFECTS: readonly string[] = [
  "squish",
  "muscle",
  "inflate",
  "crush",
  "rotate",
  "deflate",
  "cakeify",
  "baby",
  "bride",
  "classy",
  "puppy",
  "painting",
  "pirate-captain",
  "princess",
  "jungle",
  "samurai",
  "vip",
  "warrior",
  "zen",
  "assassin",
  "timelapse",
  "tsunami",
  "fire",
  "robot-face-reveal",
  "jumpscare",
  "laughing",
  "cartoon-jaw-drop",
  "crying",
  "angry-face",
  "selfie-younger-self",
  "animeify",
  "blast",
];

/** fal-ai/vidu/template-to-video — `template`. */
export const VIDU_TEMPLATES: readonly string[] = [
  "dreamy_wedding",
  "romantic_lift",
  "sweet_proposal",
  "couple_arrival",
  "cupid_arrow",
  "pet_lovers",
  "hug",
  "love_pose",
  "hair_swap",
  "youth_rewind",
  "morphlab",
  "live_photo",
  "emotionlab",
  "live_memory",
  "interaction",
  "pet_finger",
  "petal_scattered",
  "emoji_figure",
  "hair_color_change",
  "balloonman_explodes_pro",
  "jump2pool",
  "bodyshake",
  "jiggle_up",
  "shake_it_dance",
  "shake_it_down",
  "blueprint_supreme",
  "hip_twist",
  "motor_dance",
  "leg_sweep_dance",
  "shake_to_max",
  "i_know",
  "lit_bounce",
  "wave_dance",
  "chill_dance",
  "hip_flicking",
  "sakura_season",
  "rain_kiss",
  "child_memory",
  "couple_drop",
  "couple_walk",
  "flower_receive",
  "love_drop",
  "cheek_kiss",
  "carry_me",
  "blow_kiss",
  "love_fall",
  "workday_feels",
  "love_story",
  "bloom_magic",
  "box_me",
  "claw_me",
  "clayshot",
  "manga_meme",
  "quad_meme",
  "pixel_me",
  "clayshot_duo",
  "american_comic",
  "pop_art",
  "slice_therapy",
  "balloon_flyaway",
  "flying",
  "paperman",
  "pinch",
  "nap_me",
  "spin360",
  "smooth_shift",
  "paper_fall",
  "jump_to_cloud",
  "pilot",
  "sweet_dreams",
  "soul_depart",
  "punch_hit",
  "watermelon_hit",
  "split_stance_pet",
  "make_face",
  "break_glass",
  "split_stance_human",
  "covered_liquid_metal",
  "fluffy_plunge",
  "pet_belly_dance",
  "water_float",
  "relax_cut",
  "head_to_balloon",
  "cloning",
  "across_the_universe_jungle",
  "clothes_spinning_remnant",
  "across_the_universe_jurassic",
  "across_the_universe_moon",
  "fisheye_pet",
  "hitchcock_zoom",
  "cute_bangs",
  "earth_zoom_out",
  "fisheye_human",
  "drive_yacht",
  "earth_zoom_in",
  "aliens_coming",
  "drive_ferrari",
  "bjd_style",
  "virtual_fitting",
  "orbit",
  "zoom_in",
  "ai_outfit",
  "spin180",
  "orbit_dolly",
  "orbit_dolly_fast",
  "auto_spin",
  "walk_forward",
  "outfit_show",
  "zoom_in_fast",
  "zoom_out_image",
  "zoom_out_startend",
  "muscling",
  "exotic_princess",
  "beast_companion",
  "cartoon_doll",
  "golden_epoch",
  "fashion_stride",
  "star_carpet",
  "flame_carpet",
  "frost_carpet",
  "style_me",
  "tap_me",
  "saber_warrior",
  "pet2human",
  "graduation",
  "fishermen",
  "happy_birthday",
  "fairy_me",
  "grow_wings",
  "hug_from_behind",
  "run_fast",
  "background_explosion",
];
